### Question - 214

In [1]:
a = [x-2 for x in range(-1,5)]
val = lambda x:x+3
b = [val(x) for x in a]

abs(max(a) - max(b))

3

In [2]:
a,b

([-3, -2, -1, 0, 1, 2], [0, 1, 2, 3, 4, 5])

### Question - 215

In [7]:
lst = [1,1,2,3,4,5,1,3,3,3,7,9,3]
max(lst, key=lst.count)

3

In [15]:
lst = ['abcd', 'pqrs', 'xyz']
max(lst)

'xyz'

In [16]:
lst = ['abcd', 'pqrs', 'xyz']
max(lst, key=len)

'abcd'

### Question - 216

In [19]:
(1j**2).real

-1.0

In [23]:
(1j**2).imag

0.0

In [24]:
(1j+2).real, (1j+2).imag

(2.0, 1.0)

In [30]:
type(1J), type(1j)

(complex, complex)

### Question - 217

In [28]:
n = 10
print(n==int)
print(type(n)==int)

False
True


### Question - 218

In [28]:
def write(lst, text):
    lst.append(text)
    
a = 50
b = a**2
c = [a]

if b%a == 0:
    write(c,b)
else:
    write(c,a)
print(c[-1])

2500


In [29]:
a = 50
b = a**2
c = [a]

a,b,c

(50, 2500, [50])

In [30]:
if b%a == 0:
    write(c,b)
c

[50, 2500]

### Question - 219

In [31]:
values = [1,2,1,3]
nums = set(values)

def checkit(num):
    if num in nums:
        return True
    else:
        return False
    
for i in filter(checkit, values):
    print(i)

1
2
1
3


In [33]:
list(filter(checkit, values))

[1, 2, 1, 3]

### Question - 220

In [37]:
s = set('solo')
s.add('learn')
s

{'l', 'learn', 'o', 's'}

### Question - 221

In [39]:
x = 100.1205
y = str(x)[6]

print('{:.{}f}'.format(x,y))

100


### Question - 222

In [41]:
str1 = 'Superman is a hero'
def f(a):
    if a.find('hero') == -1:
        print('Found hero')
        
f(str1)

In [ ]:
# answer is no output

In [42]:
str1.find('hero')

14

### Question - 223

In [100]:
l = list(range(10))
l.pop()+max(l)

17

In [101]:
l = list(range(10))
max(l) + l.pop()

18

### Question - 224

In [102]:
numbers = [0,1,4,8,6]

digits = numbers
digits[3:] = 9
numbers

TypeError: can only assign an iterable

### Question - 225

In [122]:
v = 9

def f(v):
    v += 1
    print(v)
f(7)
print(v)

8
9


### Question - 226

In [143]:
# binary array comparison

# creating 2 binary 1d array
import numpy as np
a = np.array([1,0,1,0,1,0])
b = np.array([0,0,0,1,0,0])


# to know what percent of numbers are equal between 2 arrays
print(f'percentage of equal members is {np.mean(a == b)*100}%')

print('-----------------------------------')

# to know what percent of numbers are not equal between 2 arrays
print(f'percentage of unequal members is {np.mean(a != b)*100}%')

#this may be useful in classification models creation/validation

percentage of equal members is 33.33333333333333%
-----------------------------------
percentage of unequal members is 66.66666666666666%


In [144]:
a == b

array([False,  True, False, False, False,  True])

In [145]:
a != b

array([ True, False,  True,  True,  True, False])

### Question - 227

In [155]:
def ZeroRecursive(a):
    if a == []:
        return
    a[0] = 0
    ZeroRecursive(a[1:])
    
a = [1,2,3,4]
ZeroRecursive(a)
print(a)

[0, 2, 3, 4]


### Question - 228

In [157]:
[1,2,3,4]*-1

[]

In [158]:
[1,2,3,4]*-2

[]

### Question - 229

In [177]:
a = {1:[1,2,3]}
b = a.copy()
a[1].append(4)
a==b

True

In [179]:
a,b

({1: [1, 2, 3, 4]}, {1: [1, 2, 3]})

In [178]:
import copy
a = {1:[1,2,3]}
b = copy.deepcopy(a)
a[1].append(4)
a==b

False

In [180]:
a,b

({1: [1, 2, 3, 4]}, {1: [1, 2, 3]})

### Question - 230

In [181]:
def recf(lst, s=0):
    if len(lst) == 0:
        return s
    else:
        s += lst.pop()
        return recf(lst, s)

s = [5 for i in range(10)]

print(recf(s))

50


### Question - 231

In [ ]:
# to change dataframe indeax start from 0 to 1.

In [186]:
# creating a sample data frame
import pandas as pd
d = {'A':['a1','a2','a3','a4', 'a5'], 'B':['b1','b2','b3','b4', 'b5']}
df = pd.DataFrame(d)

print('initial dataframe')
print('-----------------')
print(df)

# to start index from 1 instead of zero

df.index += 1
print('dataframe with index start 1')
print('-----------------')
print(df)

initial dataframe
-----------------
    A   B
0  a1  b1
1  a2  b2
2  a3  b3
3  a4  b4
4  a5  b5
dataframe with index start 1
-----------------
    A   B
1  a1  b1
2  a2  b2
3  a3  b3
4  a4  b4
5  a5  b5


### Question - 232

In [188]:
# to add total against row and columns in a dataframe.

In [187]:
# creating a dataframe
import pandas as pd
d = {'A':[1,5,4,3,2], 'B':[3,2,1,6,7], 'C':[10,12,13,4,5], 'D':[25, 5, 0, 1,2]}
df = pd.DataFrame(d)

print('initial dataframe')
print('-----------------')
print(df)
print('-----------------')

# adding last row as sum of each column value
df.loc['Total',:]= df.sum(axis=0)

# adding last row as sum of each column value
df.loc[:,'Total'] = df.sum(axis=1)

print('dataframe after adding total to row and column')
print('-----------------')
print(df)
print('-----------------')

initial dataframe
-----------------
   A  B   C   D
0  1  3  10  25
1  5  2  12   5
2  4  1  13   0
3  3  6   4   1
4  2  7   5   2
-----------------
dataframe after adding total to row and column
-----------------
          A     B     C     D  Total
0       1.0   3.0  10.0  25.0   39.0
1       5.0   2.0  12.0   5.0   24.0
2       4.0   1.0  13.0   0.0   18.0
3       3.0   6.0   4.0   1.0   14.0
4       2.0   7.0   5.0   2.0   16.0
Total  15.0  19.0  44.0  33.0  111.0
-----------------


### Question - 233

In [191]:
# code to display (9,9)
a = range(10)
b = range(20)

In [192]:
list(zip(a,b))[9]

(9, 9)

### Question - 234

In [196]:
count = 0

for i in range(5):
    for j in range(i):
        count += 1
count

10

In [199]:
count = 0
for i in range(5):
    for j in range(i):
        count += 1
    print(count)

0
1
3
6
10


### Question - 235

In [203]:
s1 = frozenset([0,1,1])
s2 = frozenset([1,2,3,3,2])
s3 = {s1, s2}
total = 0

for e in s3:
    total += sum(e)
print(total)

7


In [204]:
s3

{frozenset({1, 2, 3}), frozenset({0, 1})}

### Question - 236

In [211]:
import numpy as np
a = np.array([[1,2,3], [4,5,6]])
a.T[1][0]

2

In [212]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### Question - 237

In [207]:
a = [1,2,3]
type(iter(a))

list_iterator

In [214]:
s = 'abcdefg'
y = iter(s)
type(y)

str_iterator

### Question - 238

In [209]:
x = 1024
isinstance(x,str)

False

In [213]:
x = 1024
isinstance(x,int)

True

### Question - 239

In [223]:
#to find mode by using scipy.stats

In [224]:
import scipy.stats

a = [1,1,1,2,2,3]
print(scipy.stats.mode(a))
print(scipy.stats.mode(a).mode)
print(scipy.stats.mode(a).count)

ModeResult(mode=array([1]), count=array([3]))
[1]
[3]


### Question - 240

In [226]:
a = [0,1,2,3,4,5,6,7]
for i in range(3):
    a.pop(i)
a

[1, 3, 5, 6, 7]

In [227]:
a = [0,1,2,3,4,5,6,7]
for i in range(3):
    a.pop(i)
    print(a)

[1, 2, 3, 4, 5, 6, 7]
[1, 3, 4, 5, 6, 7]
[1, 3, 5, 6, 7]


### Question - 241

In [228]:
A = [8,0,-4,-6,1]
for n in A:
    if n < 0:
        A.append(abs(n))
    x = n
x

6

In [229]:
A = [8,0,-4,-6,1]
for n in A:
    if n < 0:
        A.append(abs(n))
        print(A, n)
    x = n

[8, 0, -4, -6, 1, 4] -4
[8, 0, -4, -6, 1, 4, 6] -6


In [230]:
A = [8,0,-4,-6,1]
for n in A:
    if n < 0:
        A.append(abs(n))
        print(A, n)
    x = n
    print(x)

8
0
[8, 0, -4, -6, 1, 4] -4
-4
[8, 0, -4, -6, 1, 4, 6] -6
-6
1
4
6


### Question - 242

In [236]:
import pandas as pd
d = {'A':['a', 'b','a', 'c', 'b'], 'B':['x', 'y', 'x', 'y', 'x']}
df = pd.DataFrame(d)

print('initial dataframe')
print('-----------------')
print(df)


print('pivot table with count of A column values')
print(pd.pivot_table(df, columns=['A'], aggfunc='count', values='B'))

initial dataframe
-----------------
   A  B
0  a  x
1  b  y
2  a  x
3  c  y
4  b  x
pivot table with count of A column values
A  a  b  c
B  2  2  1


### Question - 243

In [244]:
a = {j for x in range(10) for j in range(x)}
len(a)

9

In [245]:
a

{0, 1, 2, 3, 4, 5, 6, 7, 8}

In [247]:
print([j for x in range(10) for j in range(x)])

[0, 0, 1, 0, 1, 2, 0, 1, 2, 3, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 8]


In [248]:
len([j for x in range(10) for j in range(x)])

45

### Question - 244

In [249]:
from math import sqrt as math
math(4)

#no error even if we give the module name as a variable name of function name. but not preferred.

2.0

### Question - 245

In [258]:
a = [1, [2,3]]
b = a[:]
a[0] = 3
a[1][1] = 5
print(b)

#with b = a[;] , members of inner lists are impacted. direct members are not impacted

[1, [2, 5]]


In [259]:
a = [1, [2,3]]
b = a
a[0] = 3
a[1][1] = 5
print(b)

[3, [2, 5]]


### Question - 246

In [262]:
x, y = 0,True
x = x+1
y = int(True)
id(x) == id(y)

True

In [269]:
x = 1+1+1+1
y = 6-2
z = 2**2
id(x) == id(y) == id(z)

True

In [270]:
a = 'abc'
b = 'ab' + 'c'
id(b) == id(b)

True

### Question - 247

In [2]:
def bar():
    x = 1
    def foo():
        print('x' in globals(), 'x' in locals())
    foo()
bar()

False False


In [3]:
def bar():
    x = 1
    def foo():
        print(x in globals(), x in locals())
    foo()
bar()

False False


In [5]:
def f():
    x=1
    print(x in globals(), x in locals())
f()

False False


### Question - 248

In [18]:
#column name change

#creating a sample dataframe
import pandas as pd
d = {'column 1':[1,2,3,4], 'column 2':[2,5,1,8]}
df = pd.DataFrame(d)
print('initial dataframe')
print('-----------------')
print(df)
print('-----------------')

#to rename columns
df.columns = df.columns.str.replace(' ','_')
print('dataframe with renamed columns')
print('------------------------------')
print(df)
print('------------------------------')

initial dataframe
-----------------
   column 1  column 2
0         1         2
1         2         5
2         3         1
3         4         8
-----------------
dataframe with renamed columns
------------------------------
   column_1  column_2
0         1         2
1         2         5
2         3         1
3         4         8
------------------------------


### Question - 249

In [19]:
mydict = {'foo':5, 'bar':0}
mydict.update({'foo':6})
mydict

{'foo': 6, 'bar': 0}

### Question - 250

In [21]:
def func(item):
    return len(item)

_list = ['Java', 'Python', 'C', 'R']
print(max(_list, key=func))

Python


### Question - 251

In [26]:
a=True
while a==True:
    print(a)
    a=False

True


### Question - 252

In [29]:
x = 'abc'
y = x[:]
id(x) == id(y)

True

### Question - 253

In [30]:
try:
    s = ['a', 'c']
    n = [0, 2]
    s[1:1] = 'b'
    n[1:1] = 1
except:
    pass
print(s[1], n[1])

b 2


In [31]:
s = ['a', 'c']
s[1:1] = 'b'
s

['a', 'b', 'c']

In [32]:
n = [0, 2]
n[1:1] = 1
n

TypeError: can only assign an iterable